# Matrizen und Vektoren mit NumPy

In numerischen Anwendungen sind Matrizen und Vektoren allgegenwärtig. In Python gibt es die Bibliothek NumPy, 
die mit [`ndarray`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)
einen entsprechenden Datentyp und zugehörige Rechenoperationen zur Verfügung stellt.

Wie immer in Python müssen wir die Bibliothek zunächst importieren. Es sich eingebürgert, dass Funktionen aus NumPy über das
Kürzel `np` aufgerufen werden, wir werden uns (etwas widerwillig) an diese Konvention halten. Daher beginnt ein Jupyter Notebook 
oder eine Python - Datei, in denen NumPy verwendet werden soll, immer mit der Anweisung

In [1]:
import numpy as np

## Vektoren und Matrizen

In NumPy sind Vektoren und Matrizen Spezialfälle von $n$-dimensionalen Arrays (daher der Name `ndarray`), für einen Vektor gilt $n = 1$ und für eine Matrix $n = 2$.
Uns wird das in der Regel ausreichen, aber prinzipiell kann man auch mit fünfdimensionalen Arrays rechnen.

### Erzeugen

Eine erste Möglichkeit Vektoren und Matrizen zu erzeugen besteht darin, die `array` - Funktion zu verwenden und die **Einträge direkt anzugeben**:

In [2]:
x = np.array([5, 1, 9, 2])
y = np.array([1, 2, 1, 3])
A = np.array([[1, 2, 3, 4], [7, 6, 5, 4], [6, 4, 6, 4]])
B = np.array([[2, 1], [5, 6], [9, 1]])

print('x =', x)
print('y =', y)
print('A =', A)
print('B =', B)

x = [5 1 9 2]
y = [1 2 1 3]
A = [[1 2 3 4]
 [7 6 5 4]
 [6 4 6 4]]
B = [[2 1]
 [5 6]
 [9 1]]


Der Inhalt der Arrays (dieses Wort verwenden wir als Oberbegriff) wird also in Listen angegeben, wobei für eine Matrix eine Liste von Listen verwendet wird.

Weiterhin gibt es Funktionen, mit denen sich **spezielle Matrizen und Vektoren** anlegen lassen.

In [3]:
print('Nullvektor:', np.zeros(3))
print('Nullmatrix:', np.zeros([2, 3]))
print('Einsmatrix:', np.ones([4, 2]))
print('Einheitsmatrix:', np.eye(4))

Nullvektor: [0. 0. 0.]
Nullmatrix: [[0. 0. 0.]
 [0. 0. 0.]]
Einsmatrix: [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Einheitsmatrix: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Besonders praktisch ist die Funktion `linspace`, die ein Intervall von $a$ bis $b$ in $n - 1$ gleichlange Abschnitte unterteilt.

In [4]:
z = np.linspace(1.1, 2.1, 11)
print('z=', z)

z= [1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1]


### Eigenschaften von Arrays

Ein `ndarray` - Objekt besitzt die Eigenschaft `shape`, in der die Dimensionen abgelegt sind. Hier für einen Vektor

In [5]:
print('Anzahl der Element in z:', z.shape[0])

Anzahl der Element in z: 11


und eine Matrix

In [6]:
print('Die Matrix A hat', A.shape[0], 'Zeilen und', A.shape[1], 'Spalten')

Die Matrix A hat 3 Zeilen und 4 Spalten


### 1.3 Auf Einträge zugreifen

Um auf die Einträge von Arrays zuzugreifen verwendet man (wie auch bei Python-Listen) eckige Klammern `[]`, die Indizierung
beginnt bei 0. Bei Matrizen werden Zeilen- und Spaltenindex durch ein Komma getrennt.

In [7]:
A[1, 2] = 999
print('A =', A)
print('x[0] =', x[0])

A = [[  1   2   3   4]
 [  7   6 999   4]
 [  6   4   6   4]]
x[0] = 5


Häufig möchte man in einem Rechenschritt auf mehrere Einträge eines Arrays gleichzeitig zugreifen. Hierfür gibt es zwei Möglichkeiten:

- Den Doppelpunkt-Operator
- Die Indizierung mithilfe von Integer-Arrays 

Vollständig erklärt ist das in der [NumPy-Dokumentation](https://numpy.org/doc/stable/reference/arrays.indexing.html), leider ist die
Erläuterung sehr technisch und schwer zugänglich. Im Folgenden sind daher die wichtigsten Punkte zusammengefasst.

#### Doppelpunkt-Operator

Mit der Schreibweise `start:stop` wird ein Bereich von Indizes angegeben. Dabei ist der `stop`-Index nicht enthalten (so wie bei der `range` - Funktion). Mit

In [8]:
print(z[2:5])

[1.3 1.4 1.5]


erhalten wir also die Einträge an den Positionen von 3 bis 5. Zusätzlich kann man mit `start:stop:inc` noch ein Inkrement angeben, 
zum Beispiel bekommen wir mit

In [9]:
print(z[2:7:3])

[1.3 1.6]


den dritten und den sechsten Eintrag. Lässt man hingegen `start` und/oder `stop` weg, dann erhält man den gesamten Bereich vom Anfang oder bis zum Ende. 
Damit wird es zum Beispiel möglich, auf Zeilen oder Spalten einer Matrix zuzugreifen.

In [10]:
print(z[3:])
print(A[1, :])
print(B[:, 0])

[1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1]
[  7   6 999   4]
[2 5 9]


Die Adressierung mit dem Doppelpunkt funktioniert auch bei Zuweisungen. Hier ein Beispiel:

In [11]:
A[0:2, 1:3] = np.array([[44, 88], [22, 99]])
B[1:, 1] = 777
print('A =', A)
print('B =', B)

A = [[ 1 44 88  4]
 [ 7 22 99  4]
 [ 6  4  6  4]]
B = [[  2   1]
 [  5 777]
 [  9 777]]


Es kann rechts vom Gleichheitszeichen also sowohl ein Array (dann müssen die Dimensionen passen) als auch eine einzelne Zahl stehen.

#### Index-Arrays

Mithilfe von Index-Arrays lassen sich nicht-fortlaufende Bereiche adressieren, zum Beispiel liefert das Index-Array `[2, 4, 5]` in

In [12]:
print(z[[2,4,5]])

[1.3 1.5 1.6]


den dritten, fünften und sechsten Eintrag des Arrays `z`. 

Anmerkung: Streng genommen ist `[2, 4, 5]` eine Python-Liste, aber da sind wir (und der Python-Interpreter) großzügig.

Index-Arrays funktionieren auch bei Matrizen, leider muss man hier jedoch die Index-Arrays mit `np.ix_` einpacken:

In [13]:
A = np.ones([3, 5])
print(' Vorher: A =', A)
A[np.ix_([0, 2], [1, 3])] = [[111, 999], [444, 777]]
print('Nachher: A =', A)

 Vorher: A = [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Nachher: A = [[  1. 111.   1. 999.   1.]
 [  1.   1.   1.   1.   1.]
 [  1. 444.   1. 777.   1.]]


Es gibt noch die Möglichkeit, Boolsche-Arrays zur Indizierung zu verwenden, das werden wir aber vorraussichtlich nicht benötigen.

## Rechnen mit Matrizen und Vektoren

Mit NumPy ist es möglich, Rechnungen mit Matrizen und Vektoren sehr kompakt und fast wie auf dem Papier aufzuschreiben. Allerdings muss man
bei der Bedeutung der Operatoren aufpassen.

### Mathematische Operatoren und Funktionen

Die mathematischen Operatoren sind elementweise vereinbart. Hier am Beispiel von Vektoren

In [14]:
print('x =', x, ', y =', y)
print('x + y =', x + y)
print('x * y =', x * y)
print('y / 4 =', y / 4)

x = [5 1 9 2] , y = [1 2 1 3]
x + y = [ 6  3 10  5]
x * y = [5 2 9 6]
y / 4 = [0.25 0.5  0.25 0.75]


und Matrizen

In [15]:
A = np.array([[3, 1],[8, 2],[2, 9]])
B = np.array([[7, 8],[3, 2],[5, 6]])
print('A + B =', A + B)
print('A * B =', A * B)

A + B = [[10  9]
 [11  4]
 [ 7 15]]
A * B = [[21  8]
 [24  4]
 [10 54]]


Darüber hinaus definiert NumPy die üblichen mathetischen Funktionen für Arrays. Ein Ausdruck wie zum Beispiel

$$
    1 - sin(x) + x^2
$$

kann damit in einem Rutsch für eine Liste von Zahlen berechnet werden:

In [16]:
y = 1 - np.sin(x) + x**2
print('y =', y)

y = [26.95892427  1.15852902 81.58788151  4.09070257]


### Lineare Algebra

Das **Skalarprodukt** von Vektoren lässt sich entweder mit der Funktion `dot` berechnen oder der Methode `dot` aus der `ndarray` Klasse.

In [17]:
print('x.y =', np.dot(x, y))
print('x.y =', x.dot(y))

x.y = 878.4254891676806
x.y = 878.4254891676806


Für Vektoren mit zwei oder drei Komponenten wird das **Kreuzprodukt** mit der Funktion `cross` berechnet. Für Vektoren mit zwei Komponenten
ist das Ergebnis eine Zahl (die dritte Komponente des Ergebnisvektors), sonst wieder ein Vektor mit zwei Komponenten. 

In [18]:
u = np.array([3, 2, 1])
v = np.array([5, -1, 4])
w = np.cross(u, v)

print('u =', u)
print('v =', v)
print('w = u x v =', w)
print('Natürlich gilt: u.w =', u.dot(w), ', v.w =', v.dot(w))

u = [3 2 1]
v = [ 5 -1  4]
w = u x v = [  9  -7 -13]
Natürlich gilt: u.w = 0 , v.w = 0


Sollen **Produkte** von **Matrizen und Matrizen** oder **Matrizen und Vektoren** berechnet werden, dann verwendet man den `@` - Operator. 
Natürlich müssen dann wieder die Dimensionen der Operanden zusammenpassen.

In [19]:
A = np.array([[6, 1, 9, 1], [3, 4, 1, 10]])
B = np.array([[1, 2, 3, 4], [5, 4, 3, 2], [1, 3, 1, 5], [5, 3, 1, 8]])
x = np.array([1, 3, 2, 8])

print('A =', A)
print('B =', B)
print('x = ', x)
print('AB =', A @ B)
print('Ax =', A @ x)
print('Bx =', B @ x)

A = [[ 6  1  9  1]
 [ 3  4  1 10]]
B = [[1 2 3 4]
 [5 4 3 2]
 [1 3 1 5]
 [5 3 1 8]]
x =  [1 3 2 8]
AB = [[ 25  46  31  79]
 [ 74  55  32 105]]
Ax = [35 97]
Bx = [45 39 52 80]


Die Transponierte einer Matrix `A` erhält man mit `A.T`, damit kann man dann auch wie gewohnt rechnen.

In [20]:
print('A =', A)
print('A^T =', A.T)
print('A^TA =', A.T @ A)

A = [[ 6  1  9  1]
 [ 3  4  1 10]]
A^T = [[ 6  3]
 [ 1  4]
 [ 9  1]
 [ 1 10]]
A^TA = [[ 45  18  57  36]
 [ 18  17  13  41]
 [ 57  13  82  19]
 [ 36  41  19 101]]


Zur Lösung linearer Gleichungssysteme gibt es die Funktion `solve` aus dem `linalg` - Paket von NumPy.

In [21]:
A = np.array([[5, 2], [6, 1]])
b = np.array([5, 2])
x = np.linalg.solve(A, b)

print('Lösung x =', x)
print('Zur Kontrolle: ', A @ x - b)

Lösung x = [-0.14285714  2.85714286]
Zur Kontrolle:  [0. 0.]
